using MelonLoader;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

#if !SELFCONTAINED
using BoneLib.BoneMenu;
#endif

namespace Jevil.Prefs;

/// <summary>
#if SELFCONTAINED
/// Class containing references to a MelonPreferences category.
#else
/// Class containing references to a MelonPreferences category and BoneMenu Page.
#endif
/// <para>Generated by <see cref="Preferences.Register{T}"/></para>
/// </summary>
public sealed class PrefEntries
{
    /// <summary>
    /// The MelonPrefs category made by JeviLib for your mod.
    /// </summary>
    public MelonPreferences_Category MelonPrefsCategory { get; init; }

#if !SELFCONTAINED
    /// <summary>
    /// The Page made by JeviLib for your mod.
    /// </summary>
    public Page BoneMenuPage { get; init; }
#endif

    internal readonly Dictionary<string, FieldInfo> mappedFields = new();
#if !SELFCONTAINED
    internal Page methodCategory;
    internal Page fieldCategory;
#endif
    internal readonly Dictionary<FieldInfo, Delegate> prefHooks = new();

#if SELFCONTAINED
    internal PrefEntries(MelonPreferences_Category melonPrefsCategory)
    {
        MelonPrefsCategory = melonPrefsCategory;
    }
#else
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
    internal PrefEntries(MelonPreferences_Category melonPrefsCategory, Page boneMenuPage)
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
    {
        MelonPrefsCategory = melonPrefsCategory;
        BoneMenuPage = boneMenuPage;
    }
#endif
}
